force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CL - {0000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>VI</fullName>
            </value>
            <value>
                <fullName>VII</fullName>
            </value>
            <value>
                <fullName>VIII</fullName>
            </value>
            <value>
                <fullName>IX</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect_Student__c/Prospect_Student__c.object-meta.xml
<CustomObject>
    <label>Prospect Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prospect Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect_Student__c/fields/Joining_Year__c.field-meta.xml
<CustomField>
    <fullName>Joining_Year__c</fullName>
    <label>Joining Year</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prospect_Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StudentClass__c/StudentClass__c.object-meta.xml
<CustomObject>
    <label>StudentClass</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>StudentClass Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StudentClasses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudentClass__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>StudentClasses</relationshipLabel>
    <relationshipName>StudentClasses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudentClass__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>StudentClasses</relationshipLabel>
    <relationshipName>StudentClasses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProspectStudentTriggerHandlerTest.cls
@IsTest
public class ProspectStudentTriggerHandlerTest {
    
    @isTest
    static void testWhenWeUpdateApprovedCheckStudentCreated(){
        // Given
        Class__c newCls = new Class__c();
        newCls.Class__c ='I';
        newCls.Year__c = '2022';
        
        Insert newCls;
        
        Prospect_Student__c ps = new Prospect_Student__c();
        ps.Name = 'Test';
        ps.DOB__c = Date.newInstance(1960, 2, 17);
        ps.Gender__c = 'Male';
        ps.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps.Class__c = 'I';
        ps.Status__c = 'New';
        
        Insert ps;
        
        //When
        ps.Status__c = 'Approved';
        update ps;
        
        //Then
        List<Student__c> stuList = [select id from Student__c where Name =:ps.Name and DOB__C =:ps.DOB__c and Gender__c =: ps.Gender__c ];
        system.assertEquals(1, stuList.size());
    }
    
    @isTest
    static void testWhenWeUpdateRejected(){
        // Given
        Prospect_Student__c ps = new Prospect_Student__c();
        ps.Name = 'Test';
        ps.DOB__c = Date.newInstance(1960, 2, 17);
        ps.Gender__c = 'Male';
        ps.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps.Class__c = 'I';
        ps.Status__c = 'New';
        
        Insert ps;
        
        //When
        ps.Status__c = 'Rejected';
        update ps;
        
        //Then
        List<Student__c> stuList = [select id from Student__c where Name =:ps.Name and DOB__C =:ps.DOB__c and Gender__c =: ps.Gender__c ];
        system.assertEquals(0, stuList.size());
    }
    
    @isTest
    static void testWhenWeUpdateApprovedCheckStudentClassCreated(){
        // Given
        
        Class__c newCls = new Class__c();
        newCls.Class__c ='VI';
        newCls.Year__c = '2022';
        
        Insert newCls;
        
        Prospect_Student__c ps = new Prospect_Student__c();
        ps.Name = 'Test';
        ps.DOB__c = Date.newInstance(1960, 2, 17);
        ps.Gender__c = 'Male';
        ps.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps.Class__c = 'VI';
        ps.Status__c = 'New';
        
        Insert ps;
        
        //When
        ps.Status__c = 'Approved';
        update ps;
        
        //Then
        Student__c stuList = [select id from Student__c where Name =:ps.Name and DOB__C =:ps.DOB__c and Gender__c =: ps.Gender__c];
        
        List<StudentClass__c> stuCls = [select id from StudentClass__c where Student__c =:stuList.Id AND Class__c =:newCls.id];
        system.assertEquals(1,stuCls.size());
    }
    
    @isTest
    static void testWhenWeUpdateApprovedCheckStudentCreatedBulk(){
        // Given
        Class__c newCls = new Class__c();
        newCls.Class__c ='I';
        newCls.Year__c = '2022';
        
        Insert newCls;
        
        List<Prospect_Student__c> studentList = new List<Prospect_Student__c>();
        
        Prospect_Student__c ps1 = new Prospect_Student__c();
        ps1.Name = 'Test';
        ps1.DOB__c = Date.newInstance(1960, 2, 17);
        ps1.Gender__c = 'Male';
        ps1.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps1.Class__c = 'I';
        ps1.Status__c = 'New';
        studentList.add(ps1);
        
        Prospect_Student__c ps2 = new Prospect_Student__c();
        ps2.Name = 'Test2';
        ps2.DOB__c = Date.newInstance(1960, 2, 17);
        ps2.Gender__c = 'Male';
        ps2.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps2.Class__c = 'I';
        ps2.Status__c = 'New';
        studentList.add(ps2);
        
        Insert studentList;
        
        //When
        for(Prospect_Student__c ps : studentList){
            ps.Status__c = 'Approved';   
        }
        update studentList;
        
        //Then
        List<Student__c> stuList = [select id from Student__c];
        system.assertEquals(2, stuList.size());
    }
    @isTest
    static void testWhenWeUpdateApprovedCheckStudentClassCreatedBulk(){
        // Given
        
        Class__c newCls = new Class__c();
        newCls.Class__c ='VI';
        newCls.Year__c = '2022';
        
        Insert newCls;
        
        List<Prospect_Student__c> studentList = new List<Prospect_Student__c>();
        
        Prospect_Student__c ps1 = new Prospect_Student__c();
        
        ps1.Name = 'Test';
        ps1.DOB__c = Date.newInstance(1960, 2, 17);
        ps1.Gender__c = 'Male';
        ps1.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps1.Class__c = 'VI';
        ps1.Status__c = 'New';
        studentList.add(ps1);
        
        Prospect_Student__c ps2 = new Prospect_Student__c();
        ps2.Name = 'Test2';
        ps2.DOB__c = Date.newInstance(1960, 2, 17);
        ps2.Gender__c = 'Male';
        ps2.Joining_Year__c = Date.newInstance(2022, 7, 6);
        ps2.Class__c = 'VI';
        ps2.Status__c = 'New';
        studentList.add(ps2);
        
        Insert studentList;
        
        //When
        for(Prospect_Student__c ps : studentList){
            ps.Status__c = 'Approved';   
        }
        update studentList;
        
        //Then
        
        List<StudentClass__c> stuCls = [select id from StudentClass__c];
        system.assertEquals(2,stuCls.size());
    }
}